In [20]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler

In [21]:
df = pd.read_csv("../data/healthcare_dataset.csv")

In [22]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

In [23]:
df['Hospital Stay Days'] = (
    df['Discharge Date'] - df['Date of Admission']
).dt.days

In [24]:
df.head()

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results,Hospital Stay Days
0,30,1,5,2,2024-01-31,1,18856.281306,2,2024-02-02,3,2,2
1,62,1,0,5,2019-08-20,3,33643.327287,1,2019-08-26,1,1,6
2,76,0,1,5,2022-09-22,0,27955.096079,1,2022-10-07,0,2,15
3,28,0,6,3,2020-11-18,3,37909.782410,0,2020-12-18,1,0,30
4,43,0,2,2,2022-09-19,0,14238.317814,2,2022-10-09,4,0,20

In [25]:
df.drop(
    ['Name','Doctor','Hospital','Room Number'],
    axis=1,
    inplace=True,
    errors='ignore'
)

In [26]:
df.select_dtypes(include='object').columns

Index([], dtype='object')

In [27]:
le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

In [28]:
df.head()

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results,Hospital Stay Days
0,30,1,5,2,2024-01-31,1,18856.281306,2,2024-02-02,3,2,2
1,62,1,0,5,2019-08-20,3,33643.327287,1,2019-08-26,1,1,6
2,76,0,1,5,2022-09-22,0,27955.096079,1,2022-10-07,0,2,15
3,28,0,6,3,2020-11-18,3,37909.782410,0,2020-12-18,1,0,30
4,43,0,2,2,2022-09-19,0,14238.317814,2,2022-10-09,4,0,20

In [29]:
df.to_csv("../data/healthcare_dataset.csv", index=False)

In [30]:
from sklearn.preprocessing import LabelEncoder
import pickle

encoders = {}

for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

In [31]:
df.select_dtypes(include='object').columns

Index([], dtype='object')

In [32]:
df.head()

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results,Hospital Stay Days
0,30,1,5,2,2024-01-31,1,18856.281306,2,2024-02-02,3,2,2
1,62,1,0,5,2019-08-20,3,33643.327287,1,2019-08-26,1,1,6
2,76,0,1,5,2022-09-22,0,27955.096079,1,2022-10-07,0,2,15
3,28,0,6,3,2020-11-18,3,37909.782410,0,2020-12-18,1,0,30
4,43,0,2,2,2022-09-19,0,14238.317814,2,2022-10-09,4,0,20

In [33]:
X = df.drop('Test Results', axis=1)

y = df['Test Results']

X.columns

Index(['Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission',
       'Insurance Provider', 'Billing Amount', 'Admission Type',
       'Discharge Date', 'Medication', 'Hospital Stay Days'],
      dtype='object')